import type { MedLine, SwapOption, Task } from "@/lib/types";

const sildenafilSwaps: SwapOption[] = [
  {
    id: "sil-55",
    name: "Sildenafil 55mg (Yellow/White)",
    strength: "55mg",
    form: "Capsules",
    route: "oral",
    quantity: "8 capsules",
    daysSupply: "30",
    sig: "Take 1 capsule by mouth 30–60 minutes before activity. Max 1 capsule in 24 hours.",
    price: 82.08,
  },
  {
    id: "sil-100",
    name: "Sildenafil 100mg (Blue)",
    strength: "100mg",
    form: "Tablets",
    route: "oral",
    quantity: "8 tablets",
    daysSupply: "30",
    sig: "Take 1 tablet by mouth 30–60 minutes before activity. Max 1 tablet in 24 hours.",
    price: 96.0,
  },
  {
    id: "tad-6",
    name: "Tadalafil 6 mg Tablet (Green)",
    strength: "6mg",
    form: "Chewable tablet",
    route: "chewable",
    quantity: "30 tablets",
    daysSupply: "30",
    sig: "Chew or swallow 1 tablet by mouth once daily as needed.",
    price: 71.0,
  },
];

const encloSwaps: SwapOption[] = [
  {
    id: "enc-6",
    name: "Enclomiphene 6.25mg",
    strength: "6.25mg",
    form: "Capsule",
    route: "oral",
    quantity: "30",
    daysSupply: "30",
    sig: "Take 1 capsule by mouth once daily.",
    price: 124.0,
  },
  {
    id: "enc-12",
    name: "Enclomiphene 12.5mg",
    strength: "12.5mg",
    form: "Tablet",
    route: "oral",
    quantity: "30",
    daysSupply: "30",
    sig: "Take 1 tablet by mouth once daily.",
    price: 124.0,
  },
];

const semaCatalog: SwapOption[] = [
  {
    id: "sema-m1",
    name: "Month 1: Semaglutide 2.5 mg/ml 1 ml Vial",
    strength: "2.5 mg/ml",
    form: "1 ml Vial",
    route: "subcutaneous",
    quantity: "1 vial",
    daysSupply: "30",
    sig: "Inject as directed once weekly. Titrate per protocol.",
    price: 194.0,
  },
  {
    id: "sema-m2",
    name: "Month 2: Semaglutide 2.5 mg/ml 1 ml Vial",
    strength: "2.5 mg/ml",
    form: "1 ml Vial",
    route: "subcutaneous",
    quantity: "1 vial",
    daysSupply: "30",
    sig: "Inject as directed once weekly.",
    price: 299.0,
  },
  {
    id: "sema-m3",
    name: "Month 3: Semaglutide 2.5 mg/ml 2 ml Vial",
    strength: "2.5 mg/ml",
    form: "2 ml Vial",
    route: "subcutaneous",
    quantity: "1 vial",
    daysSupply: "30",
    sig: "Inject as directed once weekly.",
    price: 299.0,
  },
  {
    id: "sema-pkg",
    name: "Semaglutide 2-Month Package (M1+M2) 2.5 mg/ml 2 ml Vial",
    strength: "2.5 mg/ml",
    form: "2 ml Vial",
    route: "subcutaneous",
    quantity: "1 vial",
    daysSupply: "60",
    sig: "Inject as directed once weekly.",
    price: 399.0,
  },
];

function lineFrom(opt: SwapOption, extra?: Partial<MedLine>): MedLine {
  return {
    id: opt.id,
    name: opt.name,
    strength: opt.strength,
    form: opt.form,
    route: opt.route,
    quantity: opt.quantity,
    daysSupply: opt.daysSupply,
    sig: opt.sig,
    price: opt.price,
    swaps: [],
    ...extra,
  };
}

export const SEED_TASKS: Task[] = [
  {
    id: "TASK6297",
    orderId: "ORD-1042",
    kind: "order",
    status: "pending",
    mode: "async",
    service: "Order evaluation",
    createdAt: "2026-08-12T16:10:00Z",
    dueAt: "2026-08-13T16:10:00Z",
    overdueDays: 14,
    paidAmount: 82.08,
    patient: {
      name: "Ahmed Larsen",
      code: "PAT5230",
      dob: "06/15/1990",
      age: 36,
      sex: "Male",
      state: "AK",
      licensed: true,
      email: "kopi@mailinator.com",
      phone: "+1 812 438 7856",
      height: "5 ft 11 in",
      weight: "204 lbs",
      bmi: "28.5",
      allergies: "No known drug allergies",
      address: "1200 W Northern Lights Blvd, Apt 14, Anchorage, AK 99503",
      newPatient: false,
      pastOrderCount: 2,
      lastOrder: "Jul 08, 2026",
    },
    lines: [
      lineFrom(sildenafilSwaps[0]!, {
        paid: true,
        paidPrice: 82.08,
        swaps: sildenafilSwaps,
      }),
    ],
    refills: 3,
    autoRefill: true,
    oneTime: false,
    maintenance: false,
    followUpDays: 30,
    providerNotes: "",
    intake: [
      { q: "Reason for request", a: "Difficulty maintaining erection, ~6 months" },
      { q: "Nitrates or nitric-oxide donors?", a: "No" },
      { q: "Cardiac history / chest pain?", a: "None reported" },
      { q: "Current medication", a: "Lisinopril 10mg daily" },
    ],
    docs: [
      { name: "intake-ahmed-larsen.pdf", kind: "Intake", date: "08/12/2026" },
      { name: "id-front.jpg", kind: "ID", date: "08/12/2026" },
    ],
    pastOrders: [
      { id: "ORD-0981", date: "Jul 08, 2026", med: "Sildenafil 55mg", status: "Delivered", amount: 82.08 },
      { id: "ORD-0902", date: "Apr 02, 2026", med: "Sildenafil 55mg", status: "Delivered", amount: 82.08 },
    ],
    prevRx: [
      {
        date: "Jul 08, 2026",
        med: "Sildenafil 55mg · 8 capsules",
        sig: "Take 1 capsule 30–60 min before activity.",
        prescriber: "Dr. Safa Ghori",
      },
    ],
    safety: {
      interactions: "No interaction flags. Intake screened against active medication list.",
      flags: [],
    },
  },
  {
    id: "TASK6402",
    kind: "protocol",
    status: "pending",
    mode: "async",
    service: "Enclomiphene medical evaluation",
    createdAt: "2026-08-21T14:02:00Z",
    dueAt: "2026-08-22T14:02:00Z",
    overdueDays: 5,
    patient: {
      name: "Karyn Love",
      code: "PAT5311",
      dob: "03/22/1988",
      age: 38,
      sex: "Female",
      state: "TX",
      licensed: true,
      email: "karyn.love@mailinator.com",
      phone: "+1 512 883 4410",
      height: "5 ft 5 in",
      weight: "162 lbs",
      bmi: "27.0",
      allergies: "Penicillin — rash",
      address: "4412 S Lamar Blvd, Austin, TX 78704",
      newPatient: true,
      pastOrderCount: 0,
    },
    protocol: {
      name: "Enclomiphene",
      price: 124,
      steps: [
        {
          id: "s1",
          n: 1,
          phase: "Ongoing",
          line: lineFrom(encloSwaps[0]!, { swaps: encloSwaps }),
        },
        {
          id: "s2",
          n: 2,
          phase: "Ongoing",
          line: lineFrom(encloSwaps[1]!, { swaps: encloSwaps }),
        },
      ],
      selectedStepId: "s1",
    },
    lines: [],
    refills: 3,
    autoRefill: true,
    oneTime: false,
    maintenance: false,
    followUpDays: 30,
    providerNotes: "",
    intake: [
      { q: "Primary goal", a: "Restore energy / libido after postpartum" },
      { q: "Last menstrual period", a: "08/01/2026" },
      { q: "History of blood clots / stroke?", a: "No" },
      { q: "Current medication", a: "Levonorgestrel IUD; vitamin D" },
    ],
    docs: [{ name: "intake-karyn-love.pdf", kind: "Intake", date: "08/21/2026" }],
    pastOrders: [],
    prevRx: [],
    safety: {
      interactions: "No drug–drug flags. Penicillin allergy is unrelated to this Rx.",
      flags: ["First prescription — new patient. Review intake before signing."],
    },
  },
  {
    id: "TASK6246",
    kind: "protocol",
    status: "pending",
    mode: "async",
    service: "Tadalafil medical evaluation",
    createdAt: "2026-08-25T07:33:00Z",
    dueAt: "2026-08-26T07:33:00Z",
    overdueDays: 1,
    patient: {
      name: "Pedro Matta",
      code: "PAT5077",
      dob: "08/07/1966",
      age: 60,
      sex: "Male",
      state: "NJ",
      licensed: true,
      email: "kenyapedro@hotmail.com",
      phone: "+1 201 640 8734",
      height: "5 ft 10 in",
      weight: "198 lbs",
      bmi: "28.4",
      allergies: "No known drug allergies",
      address: "88 River St, Hoboken, NJ 07030",
      newPatient: false,
      pastOrderCount: 1,
      lastOrder: "Jan 11, 2026",
    },
    protocol: {
      name: "Tadalafil",
      price: 71,
      steps: [
        {
          id: "s1",
          n: 1,
          phase: "Ongoing",
          line: lineFrom(sildenafilSwaps[2]!, { swaps: sildenafilSwaps }),
        },
      ],
      selectedStepId: "s1",
    },
    lines: [],
    refills: 3,
    autoRefill: true,
    oneTime: false,
    maintenance: false,
    followUpDays: 30,
    providerNotes: "",
    intake: [
      { q: "Reason for request", a: "ED, prefers daily low-dose over on-demand" },
      { q: "Nitrates or nitric-oxide donors?", a: "No" },
      { q: "Cardiac history / chest pain?", a: "None reported" },
      { q: "Current medication", a: "Atorvastatin 20mg; omeprazole 20mg" },
    ],
    docs: [
      { name: "intake-pedro-matta.pdf", kind: "Intake", date: "08/25/2026" },
      { name: "id-pedro.jpg", kind: "ID", date: "08/25/2026" },
    ],
    pastOrders: [
      { id: "ORD-0811", date: "Jan 11, 2026", med: "Tadalafil 6mg", status: "Delivered", amount: 71 },
    ],
    prevRx: [
      {
        date: "Jan 11, 2026",
        med: "Tadalafil 6mg · 30 tablets",
        sig: "Chew or swallow 1 tablet daily as needed.",
        prescriber: "Dr. Jonathan Miller",
      },
    ],
    safety: {
      interactions: "No interaction flags.",
      flags: [],
    },
  },
  {
    id: "TASK6059",
    kind: "protocol",
    status: "pending",
    mode: "sync",
    service: "Semaglutide medical evaluation",
    createdAt: "2026-07-16T14:15:00Z",
    dueAt: "2026-07-16T19:15:00Z",
    overdueDays: 41,
    patient: {
      name: "Checking Flow",
      code: "PAT4992",
      dob: "07/10/1992",
      age: 34,
      sex: "Female",
      state: "GA",
      licensed: true,
      email: "safa@123crosseven.com",
      phone: "+1 515 789 1232",
      height: "5 ft 4 in",
      weight: "214 lbs",
      bmi: "36.8",
      allergies: "No known drug allergies",
      address: "120 Piedmont Ave NE, Atlanta, GA 30303",
      newPatient: false,
      pastOrderCount: 0,
    },
    protocol: {
      name: "Semaglutide titration",
      price: 194,
      titrates: true,
      steps: [
        {
          id: "m1",
          n: 1,
          phase: "Month 1",
          line: lineFrom(semaCatalog[0]!),
        },
        {
          id: "m2",
          n: 2,
          phase: "Month 2",
          line: lineFrom(semaCatalog[1]!),
        },
        {
          id: "m3",
          n: 3,
          phase: "Month 3",
          line: lineFrom(semaCatalog[2]!),
        },
      ],
      selectedStepId: "m1",
    },
    lines: [],
    refills: 0,
    titrates: true,
    autoRefill: false,
    oneTime: false,
    maintenance: false,
    followUpDays: 28,
    providerNotes: "",
    intake: [
      { q: "Goal weight", a: "175 lbs" },
      { q: "Thyroid cancer history (self/family)?", a: "No" },
      { q: "Pancreatitis?", a: "No" },
      { q: "Current medication", a: "Metformin 500mg BID" },
    ],
    docs: [
      { name: "intake-checking-flow.pdf", kind: "Intake", date: "07/16/2026" },
      { name: "labs-cmp.pdf", kind: "Labs", date: "07/14/2026" },
    ],
    pastOrders: [],
    prevRx: [],
    safety: {
      interactions: "No GLP-1 contraindications flagged.",
      flags: ["Video visit required (sync). Confirm visit completed before signing."],
    },
  },
  {
    id: "TASK6180",
    orderId: "ORD-1044",
    kind: "order",
    status: "pending",
    mode: "async",
    service: "Refill re-authorization",
    createdAt: "2026-08-20T11:00:00Z",
    dueAt: "2026-08-21T11:00:00Z",
    overdueDays: 6,
    paidAmount: 199,
    refillOf: { cycle: 2, of: 3 },
    patient: {
      name: "Bree Carney",
      code: "PAT5188",
      dob: "11/02/1985",
      age: 40,
      sex: "Female",
      state: "FL",
      licensed: true,
      email: "bree.carney@mailinator.com",
      phone: "+1 305 441 2290",
      height: "5 ft 6 in",
      weight: "188 lbs",
      bmi: "30.3",
      allergies: "Codeine — nausea",
      address: "900 Brickell Key Blvd, Miami, FL 33131",
      newPatient: false,
      pastOrderCount: 4,
      lastOrder: "Jul 20, 2026",
    },
    lines: [
      {
        id: "oral-sema",
        name: "Oral Semaglutide 2mg",
        strength: "2mg",
        form: "Tablet",
        route: "oral",
        quantity: "30 tablets",
        daysSupply: "30",
        sig: "Take 1 tablet by mouth once daily on an empty stomach.",
        price: 199,
        paid: true,
        paidPrice: 199,
        swaps: [
          {
            id: "oral-sema",
            name: "Oral Semaglutide 2mg",
            strength: "2mg",
            form: "Tablet",
            route: "oral",
            quantity: "30 tablets",
            daysSupply: "30",
            sig: "Take 1 tablet by mouth once daily on an empty stomach.",
            price: 199,
          },
          {
            id: "oral-sema-3",
            name: "Oral Semaglutide 3mg",
            strength: "3mg",
            form: "Tablet",
            route: "oral",
            quantity: "30 tablets",
            daysSupply: "30",
            sig: "Take 1 tablet by mouth once daily on an empty stomach.",
            price: 229,
          },
        ],
      },
    ],
    refills: 0,
    titrates: true,
    autoRefill: false,
    oneTime: false,
    maintenance: false,
    followUpDays: 28,
    providerNotes: "Month 2 of oral titration. Patient tolerated 2mg. Continue.",
    intake: [
      { q: "Nausea / GI side effects?", a: "Mild week 1, resolved" },
      { q: "Weight change", a: "−9 lbs since start" },
      { q: "Thyroid cancer history?", a: "No" },
      { q: "Current medication", a: "None" },
    ],
    docs: [{ name: "intake-bree-carney.pdf", kind: "Intake", date: "06/18/2026" }],
    pastOrders: [
      { id: "ORD-1010", date: "Jul 20, 2026", med: "Oral Semaglutide 2mg", status: "Delivered", amount: 199 },
      { id: "ORD-0970", date: "Jun 18, 2026", med: "Oral Semaglutide 1mg", status: "Delivered", amount: 199 },
    ],
    prevRx: [
      {
        date: "Jul 20, 2026",
        med: "Oral Semaglutide 2mg · 30",
        sig: "Take 1 tablet daily on empty stomach.",
        prescriber: "Dr. Jonathan Miller",
      },
    ],
    safety: {
      interactions: "No interaction flags.",
      flags: [],
    },
  },
  {
    id: "TASK6310",
    kind: "prescribe",
    status: "pending",
    mode: "async",
    service: "Semaglutide medical evaluation",
    createdAt: "2026-08-26T09:40:00Z",
    dueAt: "2026-08-27T09:40:00Z",
    overdueDays: 0,
    patient: {
      name: "Maya Chen",
      code: "PAT5401",
      dob: "01/19/1991",
      age: 35,
      sex: "Female",
      state: "CA",
      licensed: true,
      email: "maya.chen@mailinator.com",
      phone: "+1 415 220 1188",
      height: "5 ft 3 in",
      weight: "198 lbs",
      bmi: "35.1",
      allergies: "No known drug allergies",
      address: "88 King St, San Francisco, CA 94107",
      newPatient: false,
      pastOrderCount: 0,
    },
    lines: [lineFrom(semaCatalog[0]!, { swaps: semaCatalog })],
    catalog: semaCatalog,
    refills: 0,
    titrates: true,
    autoRefill: false,
    oneTime: true,
    maintenance: false,
    followUpDays: 28,
    providerNotes: "",
    intake: [
      { q: "Goal weight", a: "160 lbs" },
      { q: "Thyroid cancer history (self/family)?", a: "No" },
      { q: "Pancreatitis?", a: "No" },
      { q: "Current medication", a: "Sertraline 50mg" },
    ],
    docs: [{ name: "intake-maya-chen.pdf", kind: "Intake", date: "08/26/2026" }],
    pastOrders: [],
    prevRx: [],
    safety: {
      interactions: "No GLP-1 contraindications flagged.",
      flags: [],
    },
  },
  {
    id: "TASK6411",
    orderId: "ORD-1050",
    kind: "order",
    status: "pending",
    mode: "async",
    service: "Order evaluation",
    createdAt: "2026-08-26T18:20:00Z",
    dueAt: "2026-08-27T18:20:00Z",
    overdueDays: 0,
    paidAmount: 248,
    patient: {
      name: "Ezra Ruiz",
      code: "PAT5260",
      dob: "08/05/1983",
      age: 43,
      sex: "Male",
      state: "CA",
      licensed: true,
      email: "ezra.ruiz@mailinator.com",
      phone: "+1 626 703 8739",
      height: "5 ft 9 in",
      weight: "231 lbs",
      bmi: "34.1",
      allergies: "No known drug allergies",
      address: "1114 S Grand Ave, Los Angeles, CA 90015",
      newPatient: false,
      pastOrderCount: 1,
      lastOrder: "Mar 02, 2026",
    },
    lines: [
      {
        id: "tirz",
        name: "Tirzepatide ODT 3mg",
        strength: "3mg",
        form: "ODT",
        route: "oral",
        quantity: "30 tablets",
        daysSupply: "30",
        sig: "Dissolve 1 tablet under the tongue once daily.",
        price: 199,
        paid: true,
        paidPrice: 199,
        swaps: [
          {
            id: "tirz",
            name: "Tirzepatide ODT 3mg",
            strength: "3mg",
            form: "ODT",
            route: "oral",
            quantity: "30 tablets",
            daysSupply: "30",
            sig: "Dissolve 1 tablet under the tongue once daily.",
            price: 199,
          },
          {
            id: "oral-sema-alt",
            name: "Oral Semaglutide 2mg",
            strength: "2mg",
            form: "Tablet",
            route: "oral",
            quantity: "30 tablets",
            daysSupply: "30",
            sig: "Take 1 tablet by mouth once daily on an empty stomach.",
            price: 199,
          },
        ],
      },
      {
        id: "b12",
        name: "B12 Injections 4 mg",
        strength: "4mg",
        form: "Injection",
        route: "intramuscular",
        quantity: "4 vials",
        daysSupply: "28",
        sig: "Inject 1 mL intramuscularly once weekly.",
        price: 49,
        paid: true,
        paidPrice: 49,
        swaps: [
          {
            id: "b12",
            name: "B12 Injections 4 mg",
            strength: "4mg",
            form: "Injection",
            route: "intramuscular",
            quantity: "4 vials",
            daysSupply: "28",
            sig: "Inject 1 mL intramuscularly once weekly.",
            price: 49,
          },
        ],
      },
    ],
    refills: 3,
    autoRefill: true,
    oneTime: false,
    maintenance: false,
    followUpDays: 30,
    providerNotes: "",
    intake: [
      { q: "Goal weight", a: "195 lbs" },
      { q: "Thyroid cancer history?", a: "No" },
      { q: "Pancreatitis?", a: "No" },
      { q: "Current medication", a: "Atorvastatin 20mg" },
    ],
    docs: [{ name: "intake-ezra-ruiz.pdf", kind: "Intake", date: "08/26/2026" }],
    pastOrders: [
      { id: "ORD-0888", date: "Mar 02, 2026", med: "B12 Injections 4mg", status: "Delivered", amount: 49 },
    ],
    prevRx: [],
    safety: {
      interactions: "No interaction flags.",
      flags: [],
    },
  },
  {
    id: "TASK6236",
    orderId: "ORD-1038",
    kind: "order",
    status: "declined",
    mode: "async",
    service: "Order evaluation",
    createdAt: "2026-08-21T20:13:00Z",
    dueAt: "2026-08-22T20:13:00Z",
    overdueDays: 5,
    paidAmount: 82.08,
    patient: {
      name: "Mark Test",
      code: "PAT5073",
      dob: "09/09/1992",
      age: 34,
      sex: "Male",
      state: "NY",
      licensed: true,
      email: "sakiblakhani7@gmail.com",
      phone: "+1 737 545 1324",
      height: "5 ft 11 in",
      weight: "190 lbs",
      bmi: "26.5",
      allergies: "No known drug allergies",
      address: "200 W 57th St, New York, NY 10019",
      newPatient: false,
      pastOrderCount: 0,
    },
    lines: [
      lineFrom(sildenafilSwaps[0]!, {
        paid: true,
        paidPrice: 82.08,
        declined: true,
        swaps: sildenafilSwaps,
      }),
    ],
    refills: 0,
    autoRefill: false,
    oneTime: true,
    maintenance: false,
    followUpDays: null,
    providerNotes: "Nitrate use — contraindicated.",
    declineReason: "Contraindication — nitrate use",
    intake: [
      { q: "Reason for request", a: "ED" },
      { q: "Nitrates or nitric-oxide donors?", a: "Yes — isosorbide mononitrate" },
      { q: "Cardiac history / chest pain?", a: "Stable angina, 2023 stent" },
      { q: "Current medication", a: "Isosorbide mononitrate 30mg; aspirin 81mg" },
    ],
    docs: [{ name: "intake-mark-test.pdf", kind: "Intake", date: "08/21/2026" }],
    pastOrders: [],
    prevRx: [],
    safety: {
      interactions: "Hard stop: PDE-5 inhibitor + nitrate. Do not prescribe.",
      flags: ["Contraindication — nitrate use"],
      hardStop: "PDE-5 inhibitor combined with daily nitrate therapy.",
    },
  },
];

export const DECLINE_REASONS = [
  "Contraindication / safety",
  "Incomplete intake",
  "Out of scope for this visit",
  "Patient requested cancel",
  "Duplicate order",
  "Other",
];
