/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as IdTaskIdRouteImport } from './routes/id.$taskId'
import { Route as IntakeTaskIdRouteImport } from './routes/intake.$taskId'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const IdTaskIdRoute = IdTaskIdRouteImport.update({
  id: '/id/$taskId',
  path: '/id/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeTaskIdRoute = IntakeTaskIdRouteImport.update({
  id: '/intake/$taskId',
  path: '/intake/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tasks': typeof TasksRouteWithChildren
  '/id/$taskId': typeof IdTaskIdRoute
  '/intake/$taskId': typeof IntakeTaskIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/id/$taskId': typeof IdTaskIdRoute
  '/intake/$taskId': typeof IntakeTaskIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tasks': typeof TasksRouteWithChildren
  '/id/$taskId': typeof IdTaskIdRoute
  '/intake/$taskId': typeof IntakeTaskIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tasks'
    | '/id/$taskId'
    | '/intake/$taskId'
    | '/tasks/$taskId'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/id/$taskId' | '/intake/$taskId' | '/tasks/$taskId' | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/tasks'
    | '/id/$taskId'
    | '/intake/$taskId'
    | '/tasks/$taskId'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TasksRoute: typeof TasksRouteWithChildren
  IdTaskIdRoute: typeof IdTaskIdRoute
  IntakeTaskIdRoute: typeof IntakeTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/id/$taskId': {
      id: '/id/$taskId'
      path: '/id/$taskId'
      fullPath: '/id/$taskId'
      preLoaderRoute: typeof IdTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/$taskId': {
      id: '/intake/$taskId'
      path: '/intake/$taskId'
      fullPath: '/intake/$taskId'
      preLoaderRoute: typeof IntakeTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof TasksRoute
    }
  }
}

interface TasksRouteChildren {
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TasksRoute: TasksRouteWithChildren,
  IdTaskIdRoute: IdTaskIdRoute,
  IntakeTaskIdRoute: IntakeTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
